/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Win10
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumnos = new javax.swing.JMenu();
        jmiFormularioAlumnos = new javax.swing.JMenuItem();
        jmiFormularioMateria = new javax.swing.JMenu();
        jmiFormularioMaterias = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jmiFormularioInscripcion = new javax.swing.JMenuItem();
        jmiCargaNotas = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jmiAlumnosPorMateria = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEscritorio.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jMenuAlumnos.setText("Alumno");

        jmiFormularioAlumnos.setText("Formulario de alumno");
        jmiFormularioAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioAlumnosActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jmiFormularioAlumnos);

        jMenuBar1.add(jMenuAlumnos);

        jmiFormularioMateria.setText("Materia");

        jmiFormularioMaterias.setText("Formulario de materia");
        jmiFormularioMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioMateriasActionPerformed(evt);
            }
        });
        jmiFormularioMateria.add(jmiFormularioMaterias);

        jMenuBar1.add(jmiFormularioMateria);

        jMenuAdmin.setText("Administración");

        jmiFormularioInscripcion.setText("Manejo de Inscripciones");
        jmiFormularioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioInscripcionActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jmiFormularioInscripcion);

        jmiCargaNotas.setText("Manipulación de notas");
        jmiCargaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargaNotasActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jmiCargaNotas);

        jMenuBar1.add(jMenuAdmin);

        jMenuConsultas.setText("Consultas");

        jmiAlumnosPorMateria.setText("Alumnos por Materia");
        jmiAlumnosPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumnosPorMateriaActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jmiAlumnosPorMateria);

        jMenuBar1.add(jMenuConsultas);

        jMenuSalir.setText("Salir");
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFormularioAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioAlumnosActionPerformed
        formularioAlumnos ventana = new formularioAlumnos();
        jEscritorio.add(ventana);
        ventana.show();       
        
    }//GEN-LAST:event_jmiFormularioAlumnosActionPerformed

    private void jmiFormularioMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioMateriasActionPerformed
        formularioMaterias ventana = new formularioMaterias();
        jEscritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_jmiFormularioMateriasActionPerformed

    private void jmiFormularioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioInscripcionActionPerformed
        formularioInscripcion ventana = new formularioInscripcion();
        jEscritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_jmiFormularioInscripcionActionPerformed

    private void jmiCargaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargaNotasActionPerformed
        cargaNotas ventana = new cargaNotas();
        jEscritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_jmiCargaNotasActionPerformed

    private void jmiAlumnosPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumnosPorMateriaActionPerformed
        alumnosPorMateria ventana = new alumnosPorMateria();
        jEscritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_jmiAlumnosPorMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenuItem jmiAlumnosPorMateria;
    private javax.swing.JMenuItem jmiCargaNotas;
    private javax.swing.JMenuItem jmiFormularioAlumnos;
    private javax.swing.JMenuItem jmiFormularioInscripcion;
    private javax.swing.JMenu jmiFormularioMateria;
    private javax.swing.JMenuItem jmiFormularioMaterias;
    // End of variables declaration//GEN-END:variables
}
